// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37D9caHo2AlarmAIC-aScwo3u4xS3_BM',
    appId: '1:859367860112:web:80134b8ec81a4eb8fab515',
    messagingSenderId: '859367860112',
    projectId: 'mnavb-b7a91',
    authDomain: 'mnavb-b7a91.firebaseapp.com',
    databaseURL: 'https://mnavb-b7a91-default-rtdb.firebaseio.com',
    storageBucket: 'mnavb-b7a91.firebasestorage.app',
    measurementId: 'G-Y7B60L16N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHbbatgF8lm-Us4QSC-pqsQpl-0sL770',
    appId: '1:859367860112:android:1beb2ca17efb15bbfab515',
    messagingSenderId: '859367860112',
    projectId: 'mnavb-b7a91',
    databaseURL: 'https://mnavb-b7a91-default-rtdb.firebaseio.com',
    storageBucket: 'mnavb-b7a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpkOdSfF7sld6rNF0UkpIfJP4z_Gsuo5Y',
    appId: '1:859367860112:ios:110da568f03070f1fab515',
    messagingSenderId: '859367860112',
    projectId: 'mnavb-b7a91',
    databaseURL: 'https://mnavb-b7a91-default-rtdb.firebaseio.com',
    storageBucket: 'mnavb-b7a91.firebasestorage.app',
    iosBundleId: 'com.example.mnavb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpkOdSfF7sld6rNF0UkpIfJP4z_Gsuo5Y',
    appId: '1:859367860112:ios:110da568f03070f1fab515',
    messagingSenderId: '859367860112',
    projectId: 'mnavb-b7a91',
    databaseURL: 'https://mnavb-b7a91-default-rtdb.firebaseio.com',
    storageBucket: 'mnavb-b7a91.firebasestorage.app',
    iosBundleId: 'com.example.mnavb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37D9caHo2AlarmAIC-aScwo3u4xS3_BM',
    appId: '1:859367860112:web:caa83d33fb37d2a7fab515',
    messagingSenderId: '859367860112',
    projectId: 'mnavb-b7a91',
    authDomain: 'mnavb-b7a91.firebaseapp.com',
    databaseURL: 'https://mnavb-b7a91-default-rtdb.firebaseio.com',
    storageBucket: 'mnavb-b7a91.firebasestorage.app',
    measurementId: 'G-BPYR98PD5K',
  );
}
